/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as TimingRouteImport } from './routes/timing'
import { Route as StaysRouteImport } from './routes/stays'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ItineraryRouteImport } from './routes/itinerary'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaysIdRouteImport } from './routes/stays_.$id'
import { Route as DestinationIdRouteImport } from './routes/destination.$id'

const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const TimingRoute = TimingRouteImport.update({
  id: '/timing',
  path: '/timing',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysRoute = StaysRouteImport.update({
  id: '/stays',
  path: '/stays',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ItineraryRoute = ItineraryRouteImport.update({
  id: '/itinerary',
  path: '/itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaysIdRoute = StaysIdRouteImport.update({
  id: '/stays_/$id',
  path: '/stays/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationIdRoute = DestinationIdRouteImport.update({
  id: '/destination/$id',
  path: '/destination/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/bookings': typeof BookingsRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/confirmation': typeof ConfirmationRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/insights': typeof InsightsRoute
  '/itinerary': typeof ItineraryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/marketplace': typeof MarketplaceRoute
  '/memory': typeof MemoryRoute
  '/planner': typeof PlannerRoute
  '/pricing': typeof PricingRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/stays': typeof StaysRoute
  '/timing': typeof TimingRoute
  '/transport': typeof TransportRoute
  '/destination/$id': typeof DestinationIdRoute
  '/stays/$id': typeof StaysIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/bookings': typeof BookingsRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/confirmation': typeof ConfirmationRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/insights': typeof InsightsRoute
  '/itinerary': typeof ItineraryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/marketplace': typeof MarketplaceRoute
  '/memory': typeof MemoryRoute
  '/planner': typeof PlannerRoute
  '/pricing': typeof PricingRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/stays': typeof StaysRoute
  '/timing': typeof TimingRoute
  '/transport': typeof TransportRoute
  '/destination/$id': typeof DestinationIdRoute
  '/stays/$id': typeof StaysIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/bookings': typeof BookingsRoute
  '/checkout': typeof CheckoutRoute
  '/community': typeof CommunityRoute
  '/confirmation': typeof ConfirmationRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/insights': typeof InsightsRoute
  '/itinerary': typeof ItineraryRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRoute
  '/marketplace': typeof MarketplaceRoute
  '/memory': typeof MemoryRoute
  '/planner': typeof PlannerRoute
  '/pricing': typeof PricingRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/stays': typeof StaysRoute
  '/timing': typeof TimingRoute
  '/transport': typeof TransportRoute
  '/destination/$id': typeof DestinationIdRoute
  '/stays_/$id': typeof StaysIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/assistant'
    | '/bookings'
    | '/checkout'
    | '/community'
    | '/confirmation'
    | '/dashboard'
    | '/explore'
    | '/insights'
    | '/itinerary'
    | '/live'
    | '/login'
    | '/maps'
    | '/marketplace'
    | '/memory'
    | '/planner'
    | '/pricing'
    | '/saved'
    | '/signup'
    | '/stays'
    | '/timing'
    | '/transport'
    | '/destination/$id'
    | '/stays/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/assistant'
    | '/bookings'
    | '/checkout'
    | '/community'
    | '/confirmation'
    | '/dashboard'
    | '/explore'
    | '/insights'
    | '/itinerary'
    | '/live'
    | '/login'
    | '/maps'
    | '/marketplace'
    | '/memory'
    | '/planner'
    | '/pricing'
    | '/saved'
    | '/signup'
    | '/stays'
    | '/timing'
    | '/transport'
    | '/destination/$id'
    | '/stays/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/assistant'
    | '/bookings'
    | '/checkout'
    | '/community'
    | '/confirmation'
    | '/dashboard'
    | '/explore'
    | '/insights'
    | '/itinerary'
    | '/live'
    | '/login'
    | '/maps'
    | '/marketplace'
    | '/memory'
    | '/planner'
    | '/pricing'
    | '/saved'
    | '/signup'
    | '/stays'
    | '/timing'
    | '/transport'
    | '/destination/$id'
    | '/stays_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  BookingsRoute: typeof BookingsRoute
  CheckoutRoute: typeof CheckoutRoute
  CommunityRoute: typeof CommunityRoute
  ConfirmationRoute: typeof ConfirmationRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  InsightsRoute: typeof InsightsRoute
  ItineraryRoute: typeof ItineraryRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  MapsRoute: typeof MapsRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MemoryRoute: typeof MemoryRoute
  PlannerRoute: typeof PlannerRoute
  PricingRoute: typeof PricingRoute
  SavedRoute: typeof SavedRoute
  SignupRoute: typeof SignupRoute
  StaysRoute: typeof StaysRoute
  TimingRoute: typeof TimingRoute
  TransportRoute: typeof TransportRoute
  DestinationIdRoute: typeof DestinationIdRoute
  StaysIdRoute: typeof StaysIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timing': {
      id: '/timing'
      path: '/timing'
      fullPath: '/timing'
      preLoaderRoute: typeof TimingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays': {
      id: '/stays'
      path: '/stays'
      fullPath: '/stays'
      preLoaderRoute: typeof StaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itinerary': {
      id: '/itinerary'
      path: '/itinerary'
      fullPath: '/itinerary'
      preLoaderRoute: typeof ItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stays_/$id': {
      id: '/stays_/$id'
      path: '/stays/$id'
      fullPath: '/stays/$id'
      preLoaderRoute: typeof StaysIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destination/$id': {
      id: '/destination/$id'
      path: '/destination/$id'
      fullPath: '/destination/$id'
      preLoaderRoute: typeof DestinationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  BookingsRoute: BookingsRoute,
  CheckoutRoute: CheckoutRoute,
  CommunityRoute: CommunityRoute,
  ConfirmationRoute: ConfirmationRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  InsightsRoute: InsightsRoute,
  ItineraryRoute: ItineraryRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  MapsRoute: MapsRoute,
  MarketplaceRoute: MarketplaceRoute,
  MemoryRoute: MemoryRoute,
  PlannerRoute: PlannerRoute,
  PricingRoute: PricingRoute,
  SavedRoute: SavedRoute,
  SignupRoute: SignupRoute,
  StaysRoute: StaysRoute,
  TimingRoute: TimingRoute,
  TransportRoute: TransportRoute,
  DestinationIdRoute: DestinationIdRoute,
  StaysIdRoute: StaysIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
